// Writes src/generated/config.js: the two PUBLIC values the browser needs to reach Supabase (project URL and anon key).
// They come from .env or the environment. With nothing set the file says "not connected" and the app runs in demo mode
// (data kept in this browser, no sign-in), which is also what the tests and CI use.
// The service-role key and DATABASE_URL are never written here.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const env = { ...process.env };
try {
  for (const line of readFileSync(resolve(root, '.env'), 'utf8').split('\n')) {
    const m = line.match(/^([A-Z_]+)=(.*)$/);
    if (m && env[m[1]] === undefined) env[m[1]] = m[2].trim();
  }
} catch { /* no .env */ }

// accept the project URL with or without a trailing /rest/v1/
const url = (env.SUPABASE_URL || '').replace(/\/rest\/v1\/?$/, '').replace(/\/$/, '');
const key = env.SUPABASE_ANON_KEY || '';
const connected = Boolean(url && key);
const out = resolve(root, 'src/generated/config.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `/* GENERATED by scripts/gen-config.mjs from .env. Public values only. Do not edit or commit. */\nconst APP_CONFIG=${JSON.stringify({ supabaseUrl: url, anonKey: key })};\n`);
console.log(connected ? `src/generated/config.js  (connected to ${url})` : 'src/generated/config.js  (not connected: demo mode)');
